language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: vitalie.andries@gmail.com
  api_key:
    secure: b9HA7Y3H5RDoD4RhtiNi4dVI5pmvN3/Pb2fbKiEWWFBHWSJda/lbJ2tsdJmemAsvyLQfhARsGF8m2gMPeoJ23S6X8Ncfwr8gZDAj2FBbMSEpBHTXojYsIHPAqWg2KX64ekiMEK2D2Gc9Ns5AGQH+ohg533/psdXGWTuVJi73GiTobI4x39MDew8Eh1DgopYy3fOMH7g1EMQBqrb1QlZ55N9yHuiJrsu/trp5bAITLPo8zX51VbppiiwtIJxFmgTafqbr25Pzxi8usNbyEo7FA6lots2yWIjM9bJB18ojQgyRaJRvHrk1YhKfLUIHZ2RdCbusk7biLBRAMHxmEIPfSqGo2w/0ymDnjPAJ08r3qIC2jMu71NftE4vEuZtlolhNCuJuNNPAZ9vbN0NCX2gOt0tvTplPqeDWml2KDrhnpJKG5sShY5TRT/c6SbXnKSgEmgcRA/4TGdMgP3gnb96MhCNkcJ0LNA+eb6s5s/C4kC4DgLLL4NwTjAXljqD8gRPYxFbcO5xXN3FwboNpxiP7jGzYf62FJDlEooEWqE9z+6LlgMYVycmprIirKUyuxl7i2qv4eBGCzzh6LSsPyKljpr1mroujnKs+ncB7iIs1ZHq75CI1PojMN9guN6nK+atOsqTw+hYj48o3sAPbxSqFb03WGh69RIp6QG7G+YN2NNI=
  on:
    tags: true
    repo: vandriesh/errtracker-lib
